# Generated by Django 4.0.6 on 2022-07-24 19:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='-', max_length=100, unique=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='-', max_length=50)),
                ('descricao', models.CharField(default='Filial-Sede', max_length=50, verbose_name='Descrição')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_mov', models.CharField(default='', max_length=20, verbose_name='Entrada')),
                ('status_prod', models.CharField(default='', max_length=20, verbose_name='Saída')),
            ],
        ),
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='-', max_length=50, verbose_name='Produto')),
                ('est_inic', models.IntegerField(default=0, verbose_name='Estoque Inicial')),
                ('est_min', models.IntegerField(default=0, verbose_name='Estoque Mínimo')),
                ('descricao', models.CharField(blank=True, default='nenhuma', max_length=150, null=True, verbose_name='Descrição')),
                ('unid_medida', models.DecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='Unidade de Medida')),
                ('detalhes', models.CharField(default='nenhum', max_length=100)),
                ('cod_produto', models.IntegerField(default=0, unique=True, verbose_name='Estoque Mínimo')),
                ('categoria_f_m', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Cadastro.categoria')),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Cadastro.local')),
            ],
        ),
        migrations.CreateModel(
            name='Movimentacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_movimetacao', models.DateField(verbose_name='Dt_Movimentação')),
                ('categoria_f_m', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Cadastro.categoria')),
                ('locais', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Cadastro.local')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Cadastro.produtos')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Cadastro.status')),
            ],
        ),
    ]
