# Generated by Django 4.0.6 on 2022-07-31 18:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='-', max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='pdf/')),
            ],
        ),
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='-', max_length=50)),
                ('descricao', models.CharField(default='Filial-Sede', max_length=50, verbose_name='Descrição')),
            ],
        ),
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='-', max_length=50, verbose_name='Produto')),
                ('est_inic', models.IntegerField(default=0, verbose_name='Estoque Inicial')),
                ('est_min', models.IntegerField(default=0, verbose_name='Estoque Mínimo')),
                ('descricao', models.TextField(blank=True, max_length=150, null=True, verbose_name='Descrição')),
                ('unid_medida', models.CharField(choices=[('un', 'Unidade'), ('cm', 'Centimetros'), ('mm', 'Milimetros'), ('m', 'Metros')], max_length=2, null=True, verbose_name='Unidade de Medida')),
                ('cod_produto', models.CharField(default='-', max_length=120, unique=True, verbose_name='CÓD')),
                ('categoria_f_m', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Cadastro.categoria', verbose_name='Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_mov', models.CharField(default='', max_length=20, verbose_name='Entrada')),
                ('status_prod', models.CharField(default='', max_length=20, verbose_name='Saída')),
            ],
        ),
        migrations.CreateModel(
            name='Solicitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='Pendente', max_length=11, verbose_name='Status')),
                ('quantidade_solicita', models.DecimalField(decimal_places=2, max_digits=6, null=True, verbose_name='Quantidade')),
                ('observacao_solicita', models.TextField(null=True, verbose_name='Obs')),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Cadastro.categoria', verbose_name='Categoria')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('destino', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Cadastro.local', verbose_name='Destino')),
                ('produto_solicita', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Cadastro.produtos', verbose_name='Produto')),
            ],
        ),
        migrations.CreateModel(
            name='Movimentacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_movimetacao', models.DateField(verbose_name='Dt_Movimentação')),
                ('categoria_f_m', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Cadastro.categoria')),
                ('locais', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Cadastro.local')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Cadastro.produtos')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Cadastro.status')),
            ],
        ),
    ]
