# Generated by Django 4.0.6 on 2022-07-24 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cadastro', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produtos',
            name='detalhes',
        ),
    ]
