# Generated by Django 4.0.6 on 2022-07-24 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cadastro', '0004_alter_produtos_cod_produto_alter_produtos_descricao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produtos',
            name='local',
        ),
        migrations.AlterField(
            model_name='produtos',
            name='categoria_f_m',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Cadastro.categoria', verbose_name='Categoria'),
        ),
    ]
