# Generated by Django 4.0.6 on 2022-07-24 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cadastro', '0005_remove_produtos_local_alter_produtos_categoria_f_m'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='usuario',
        ),
    ]
