# Generated by Django 4.0.6 on 2022-07-25 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cadastro', '0007_dados'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dados',
            name='arquivo',
            field=models.FileField(upload_to='pdf/'),
        ),
    ]
