# Generated by Django 4.0.6 on 2022-07-28 02:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cadastro', '0008_alter_dados_arquivo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_solicita', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Quantidade')),
                ('observacao_solicita', models.TextField(verbose_name='Obs')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Cadastro.categoria', verbose_name='Destino')),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Cadastro.local', verbose_name='Destino')),
                ('produto_solicita', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Cadastro.produtos', verbose_name='Produto')),
            ],
        ),
    ]
