# Generated by Django 4.0.6 on 2022-07-28 03:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cadastro', '0009_solicitacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacao',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Cadastro.categoria', verbose_name='Destino'),
        ),
        migrations.AlterField(
            model_name='solicitacao',
            name='destino',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Cadastro.local', verbose_name='Destino'),
        ),
        migrations.AlterField(
            model_name='solicitacao',
            name='observacao_solicita',
            field=models.TextField(null=True, verbose_name='Obs'),
        ),
        migrations.AlterField(
            model_name='solicitacao',
            name='produto_solicita',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Cadastro.produtos', verbose_name='Produto'),
        ),
        migrations.AlterField(
            model_name='solicitacao',
            name='quantidade_solicita',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True, verbose_name='Quantidade'),
        ),
    ]
