# Generated by Django 4.0.6 on 2022-07-28 03:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cadastro', '0010_alter_solicitacao_categoria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacao',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Cadastro.categoria', verbose_name='Categoria'),
        ),
    ]
