# Generated by Django 4.0.6 on 2022-07-28 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cadastro', '0011_alter_solicitacao_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtos',
            name='unid_medida',
            field=models.CharField(choices=[('un', 'Unidade'), ('cm', 'Centimetros'), ('mm', 'Milimetros'), ('m', 'Metros')], max_length=2, null=True, verbose_name='Unidade de Medida'),
        ),
    ]
