# Generated by Django 4.0.6 on 2022-08-09 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cadastro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='local',
            name='descricao',
            field=models.CharField(choices=[('FILIAL', 'filial'), ('MATRIZ', 'matriz')], default='selecione uma descrição', max_length=50, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='local',
            name='nome',
            field=models.CharField(default=' ', max_length=50),
        ),
    ]
