# Generated by Django 4.0.6 on 2022-08-17 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cadastro', '0003_remove_local_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtos',
            name='nome',
            field=models.CharField(default=' ', max_length=50, verbose_name='Produto'),
        ),
    ]
