# Generated by Django 4.0.6 on 2022-08-20 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cadastro', '0004_alter_produtos_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtos',
            name='estoque_atl',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Estoque atualizado'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='solicitacao',
            name='quantidade_solicita',
            field=models.IntegerField(default=0, null=True, verbose_name='Quantidade'),
        ),
    ]
