# Generated by Django 4.0.6 on 2022-08-20 23:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cadastro', '0005_produtos_estoque_atl_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacao',
            name='produto_solicita',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Cadastro.produtos', verbose_name='Produto'),
        ),
    ]
