# Generated by Django 4.0.6 on 2022-08-24 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cadastro', '0006_alter_solicitacao_produto_solicita'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produtos',
            options={'ordering': ('nome',)},
        ),
    ]
