# Generated by Django 4.0.6 on 2022-08-28 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cadastro', '0007_alter_produtos_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'ordering': ('nome',)},
        ),
        migrations.AlterModelOptions(
            name='solicitacao',
            options={'ordering': ('-data',)},
        ),
        migrations.AddField(
            model_name='solicitacao',
            name='data',
            field=models.DateField(auto_now=True),
        ),
    ]
