# Generated by Django 4.0.6 on 2022-09-05 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cadastro', '0009_produtos_criado_por'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtos',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Cadastro.local'),
        ),
    ]
