# Generated by Django 4.0.6 on 2022-09-05 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cadastro', '0010_alter_produtos_criado_por'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produtos',
            old_name='criado_por',
            new_name='estoque_local',
        ),
    ]
