# Generated by Django 4.0.6 on 2022-09-13 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cadastro', '0011_rename_criado_por_produtos_estoque_local'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solicitacao',
            options={'ordering': ('data',)},
        ),
    ]
