# Generated by Django 4.0.6 on 2022-09-13 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cadastro', '0012_alter_solicitacao_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solicitacao',
            options={'ordering': ('-data',)},
        ),
    ]
