# Generated by Django 4.0.6 on 2022-10-15 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cadastro', '0014_auxiliar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auxiliar',
            name='local_produto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Cadastro.local'),
        ),
        migrations.AlterField(
            model_name='auxiliar',
            name='produto_detalhes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Cadastro.produtos'),
        ),
        migrations.AlterField(
            model_name='auxiliar',
            name='produto_solicitacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Cadastro.solicitacao'),
        ),
        migrations.AlterField(
            model_name='auxiliar',
            name='produto_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Cadastro.status'),
        ),
    ]
