# Generated by Django 4.0.6 on 2022-10-16 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cadastro', '0016_auxiliar_categoria_produto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Auxiliar',
        ),
    ]
