# Generated by Django 4.0.6 on 2022-10-20 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cadastro', '0017_delete_auxiliar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtos',
            name='estoque_atl',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Estoque atualizado'),
        ),
    ]
