# Generated by Django 4.0.6 on 2022-10-21 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cadastro', '0018_alter_produtos_estoque_atl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtos',
            name='estoque_atl',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Estoque atual'),
        ),
    ]
