# Generated by Django 4.0.6 on 2022-10-21 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cadastro', '0020_criarsolicitacao_alter_solicitacao_criado_por'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CriarSolicitacao',
        ),
    ]
