# Generated by Django 4.0.6 on 2022-11-18 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cadastro', '0021_delete_criarsolicitacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField(default=0, null=True, verbose_name='Código')),
                ('nome', models.CharField(default=' ', max_length=50)),
                ('perc_encargos', models.IntegerField(verbose_name='Percentual de Encargos Empresa')),
                ('visivel', models.CharField(choices=[('Compra de dívida', 'Compra de dívida'), ('Operações', 'Operações'), ('Ambos', 'Ambos')], max_length=16, null=True, verbose_name='Visível')),
                ('perc_desconto_saldo_devedor', models.IntegerField(verbose_name='Percentual de Saldo Devedor')),
                ('visualizar_app', models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], max_length=3, null=True, verbose_name='visualizar no App de Cliente')),
                ('visivel_corretores', models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], max_length=3, null=True, verbose_name='visualizar no App de Cliente')),
                ('pagar_bonus_junto_comissao', models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], max_length=3, null=True, verbose_name='Pagar bônus junto da comissão')),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Cadastro.categoria')),
            ],
        ),
    ]
