# Generated by Django 4.0.6 on 2022-11-18 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cadastro', '0022_banco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banco',
            name='perc_desconto_saldo_devedor',
            field=models.IntegerField(verbose_name='% de Saldo Devedor'),
        ),
        migrations.AlterField(
            model_name='banco',
            name='visivel_corretores',
            field=models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], max_length=3, null=True, verbose_name='visível aos corretores'),
        ),
    ]
