# Generated by Django 4.0.6 on 2022-11-18 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cadastro', '0023_alter_banco_perc_desconto_saldo_devedor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banco',
            name='perc_encargos',
            field=models.IntegerField(verbose_name='% de Encargos Empresa'),
        ),
        migrations.AlterField(
            model_name='banco',
            name='visualizar_app',
            field=models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], max_length=3, null=True, verbose_name='visual. no App Cliente'),
        ),
    ]
