# Generated by Django 4.0.6 on 2022-11-19 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cadastro', '0024_alter_banco_perc_encargos_alter_banco_visualizar_app'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banco',
            name='pagar_bonus_junto_comissao',
            field=models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], max_length=3, null=True, verbose_name='Pagar bônus com comissão'),
        ),
        migrations.AlterField(
            model_name='banco',
            name='perc_desconto_saldo_devedor',
            field=models.IntegerField(verbose_name='Saldo Devedor (%)'),
        ),
        migrations.AlterField(
            model_name='banco',
            name='perc_encargos',
            field=models.IntegerField(verbose_name='Encargos Empresa (%)'),
        ),
    ]
