# Generated by Django 4.0.6 on 2022-11-27 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cadastro', '0025_alter_banco_pagar_bonus_junto_comissao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrupoComissao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default=' ', max_length=50)),
                ('perc_comissao', models.IntegerField(verbose_name='Percentual')),
                ('status_comissao', models.CharField(choices=[('Ativo', 'Ativo'), ('Inativo', 'Inativo')], max_length=7, null=True, verbose_name='status')),
                ('observacao_comissao', models.TextField(null=True, verbose_name='Observações')),
            ],
        ),
    ]
