# Generated by Django 4.0.6 on 2022-11-27 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cadastro', '0026_grupocomissao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'ordering': ('nome_categoria',)},
        ),
        migrations.RenameField(
            model_name='categoria',
            old_name='nome',
            new_name='nome_categoria',
        ),
        migrations.CreateModel(
            name='Setor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='-', max_length=100, unique=True)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cadastro.categoria')),
            ],
            options={
                'ordering': ('nome',),
            },
        ),
    ]
