# Generated by Django 4.0.6 on 2022-11-27 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cadastro', '0027_alter_categoria_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setor',
            name='departamento',
        ),
    ]
