# Generated by Django 4.0.6 on 2022-11-27 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0028_rename_banco_loginbanco_banco_l_setor_and_more'),
        ('Cadastro', '0028_remove_setor_departamento'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Setor',
        ),
    ]
