# Generated by Django 4.0.6 on 2022-12-04 22:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cadastro', '0029_delete_setor'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicoBanco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produto', models.CharField(default=' ', max_length=50, null=True, verbose_name='Produto')),
                ('banco', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Cadastro.banco')),
            ],
        ),
    ]
