# Generated by Django 4.0.6 on 2022-08-21 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='setor',
            field=models.CharField(choices=[{'id': 1, 'name': 'Administrador'}, {'id': 2, 'name': 'Filial'}], max_length=20, null=True, verbose_name='Permissões'),
        ),
    ]
