# Generated by Django 4.0.6 on 2022-08-22 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0004_perfil_permissao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='permissao',
        ),
    ]
