# Generated by Django 4.0.6 on 2022-08-28 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0009_remove_perfil_grupo'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='local',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
