# Generated by Django 4.0.6 on 2022-09-06 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('Usuarios', '0011_perfil_grupo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='grupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auth.group'),
        ),
    ]
