# Generated by Django 4.0.6 on 2022-10-27 00:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cadastro', '0021_delete_criarsolicitacao'),
        ('Usuarios', '0013_remove_perfil_grupo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='local',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Cadastro.local'),
        ),
    ]
