# Generated by Django 4.0.6 on 2022-10-27 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cadastro', '0021_delete_criarsolicitacao'),
        ('Usuarios', '0014_alter_perfil_local'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='local',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='Cadastro.local'),
            preserve_default=False,
        ),
    ]
