# Generated by Django 4.0.6 on 2022-10-27 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0015_alter_perfil_local'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='local',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
