# Generated by Django 4.0.6 on 2022-11-05 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0017_perfil_data_nascimento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfil',
            old_name='data_nascimento',
            new_name='data_nasc',
        ),
    ]
