# Generated by Django 4.0.6 on 2022-11-17 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0018_rename_data_nascimento_perfil_data_nasc'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='Bairro',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='perfil',
            name='Cidade',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='perfil',
            name='Estado',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='perfil',
            name='complemento',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='perfil',
            name='data_emissao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='logradouro',
            field=models.CharField(default='', max_length=45),
        ),
        migrations.AddField(
            model_name='perfil',
            name='nome_mae',
            field=models.CharField(default='', max_length=30, verbose_name='Nome da Mãe'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='nome_pai',
            field=models.CharField(default='', max_length=30, verbose_name='Nome da Pai'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='numero_casa',
            field=models.IntegerField(default=0, verbose_name='Número'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='org_exp',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='rg',
            field=models.CharField(max_length=14, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='tipo_contato',
            field=models.CharField(choices=[('Residencial', 'Residencial'), ('Comercial', 'Comercial'), ('Celular', 'Celular'), ('WhatsApp', 'WhatsApp')], max_length=11, null=True, verbose_name='Tipo'),
        ),
    ]
