# Generated by Django 4.0.6 on 2022-11-23 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0019_perfil_bairro_perfil_cidade_perfil_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='dt_cadastro',
            field=models.DateField(blank=True, null=True, verbose_name='Data de cadastro'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='dt_inicio',
            field=models.DateField(blank=True, null=True, verbose_name='Data de inicio'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='complemento',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='cpf',
            field=models.CharField(max_length=14, null=True, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='nome_mae',
            field=models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='Nome da Mãe'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='nome_pai',
            field=models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='Nome da Pai'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='rg',
            field=models.CharField(max_length=14, null=True, verbose_name='RG'),
        ),
    ]
