# Generated by Django 4.0.6 on 2022-11-23 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0020_perfil_dt_cadastro_perfil_dt_inicio_perfil_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfil',
            old_name='org_exp',
            new_name='org_exped',
        ),
    ]
