# Generated by Django 4.0.6 on 2022-11-23 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0021_rename_org_exp_perfil_org_exped'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfil',
            old_name='Bairro',
            new_name='bairro',
        ),
        migrations.RenameField(
            model_name='perfil',
            old_name='Cidade',
            new_name='cidade',
        ),
        migrations.RenameField(
            model_name='perfil',
            old_name='complemento',
            new_name='complemento_casa',
        ),
        migrations.RenameField(
            model_name='perfil',
            old_name='data_emissao',
            new_name='data_emiss',
        ),
        migrations.RenameField(
            model_name='perfil',
            old_name='Estado',
            new_name='estado',
        ),
        migrations.AddField(
            model_name='perfil',
            name='cep',
            field=models.CharField(default='', max_length=15),
        ),
    ]
