# Generated by Django 4.0.6 on 2022-11-24 01:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Usuarios', '0022_rename_bairro_perfil_bairro_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='email',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='telefone',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='tipo_contato',
        ),
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefone', models.CharField(max_length=16, null=True)),
                ('email_p', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail pessoal')),
                ('email_c', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail pessoal')),
                ('tipo_contato', models.CharField(choices=[('Residencial', 'Residencial'), ('Comercial', 'Comercial'), ('Celular', 'Celular'), ('WhatsApp', 'WhatsApp')], max_length=11, null=True, verbose_name='Tipo')),
                ('proprietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
