# Generated by Django 4.0.6 on 2022-11-24 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0023_remove_perfil_email_remove_perfil_telefone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contato',
            name='proprietario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuarios.perfil'),
        ),
    ]
