# Generated by Django 4.0.6 on 2022-11-26 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0024_alter_contato_proprietario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contato',
            name='email_c',
        ),
        migrations.RemoveField(
            model_name='contato',
            name='email_p',
        ),
        migrations.AddField(
            model_name='perfil',
            name='email_c',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail corporativo'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='email_p',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail pessoal'),
        ),
        migrations.AlterField(
            model_name='contato',
            name='telefone',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='contato',
            name='tipo_contato',
            field=models.CharField(blank=True, choices=[('Residencial', 'Residencial'), ('Comercial', 'Comercial'), ('Celular', 'Celular'), ('WhatsApp', 'WhatsApp')], max_length=11, null=True, verbose_name='Tipo'),
        ),
    ]
