# Generated by Django 4.0.6 on 2022-11-27 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0025_remove_contato_email_c_remove_contato_email_p_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='email_c',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='email_p',
        ),
        migrations.AddField(
            model_name='contato',
            name='email_c',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail corporativo'),
        ),
        migrations.AddField(
            model_name='contato',
            name='email_p',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail pessoal'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='dt_deligamento',
            field=models.DateField(blank=True, null=True, verbose_name='Data de desligamento'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='dt_efetivacao',
            field=models.DateField(blank=True, null=True, verbose_name='Dt. de Efetivação'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='dt_inicio_est',
            field=models.DateField(blank=True, null=True, verbose_name='Dt. de Inicio'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='dt_inicio_serv',
            field=models.DateField(blank=True, null=True, verbose_name='Dt. de Inicio'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='dt_termino_contrato',
            field=models.DateField(blank=True, null=True, verbose_name='Termino de contrato'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='fase_1_est',
            field=models.DateField(blank=True, null=True, verbose_name='1° fase'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='fase_2_est',
            field=models.DateField(blank=True, null=True, verbose_name='2° fase'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='status_contrato',
            field=models.CharField(blank=True, choices=[('Concluído', 'Concluído'), ('Pendente', 'Pendente')], max_length=11, null=True, verbose_name='Tipo'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='tipo_demissao',
            field=models.DateField(blank=True, choices=[('Sem justa causa', 'Sem justa causa'), ('Com justa causa', 'Com justa causa'), ('Pedido de demissão', 'Pedido de demissão'), ('Acordo', 'Acordo'), ('consensual', 'consensual')], max_length=18, null=True, verbose_name='Tipo de Demissão'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='dt_inicio',
            field=models.DateField(blank=True, null=True, verbose_name='Dt. de Inicio'),
        ),
    ]
