# Generated by Django 4.0.6 on 2022-11-27 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cadastro', '0027_alter_categoria_options_and_more'),
        ('Usuarios', '0026_remove_perfil_email_c_remove_perfil_email_p_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginBanco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario_banco', models.CharField(blank=True, max_length=16, null=True, verbose_name='Usuário')),
                ('senha_banco', models.CharField(blank=True, max_length=16, null=True, verbose_name='Senha')),
                ('status_b', models.CharField(blank=True, choices=[('Ativo', 'Ativo'), ('Inativo', 'Inativo')], max_length=7, null=True, verbose_name='Status')),
                ('banco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cadastro.banco')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cadastro.setor')),
                ('usuario_perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuarios.perfil')),
            ],
        ),
    ]
