# Generated by Django 4.0.6 on 2022-11-27 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cadastro', '0028_remove_setor_departamento'),
        ('Usuarios', '0027_loginbanco'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loginbanco',
            old_name='banco',
            new_name='banco_l',
        ),
        migrations.CreateModel(
            name='Setor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='-', max_length=100, unique=True)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cadastro.categoria')),
                ('usuario_perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuarios.perfil')),
            ],
            options={
                'ordering': ('nome',),
            },
        ),
        migrations.AlterField(
            model_name='loginbanco',
            name='perfil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuarios.setor'),
        ),
    ]
