# Generated by Django 4.0.6 on 2022-12-04 01:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cadastro', '0029_delete_setor'),
        ('Usuarios', '0028_rename_banco_loginbanco_banco_l_setor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginbanco',
            name='banco_l',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cadastro.banco', verbose_name='Banco'),
        ),
    ]
