# Generated by Django 4.0.6 on 2022-12-04 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0029_alter_loginbanco_banco_l'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setor',
            name='usuario_perfil',
        ),
    ]
