# Generated by Django 4.0.6 on 2022-12-04 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0030_remove_setor_usuario_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='grupo_comissiao',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
