# Generated by Django 4.0.6 on 2022-12-07 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0031_perfil_grupo_comissiao'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='email_p',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email Pessoal'),
        ),
    ]
