# Generated by Django 4.0.6 on 2022-09-05 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cadastro', '0008_alter_categoria_options_alter_solicitacao_options_and_more'),
        ('estoque', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estoque',
            name='est_local',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='Cadastro.local'),
        ),
    ]
