# Generated by Django 4.0.6 on 2022-09-12 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0002_estoque_est_local'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estoqueitens',
            name='saldo',
        ),
    ]
