# Generated by Django 4.0.6 on 2022-09-12 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0003_remove_estoqueitens_saldo'),
    ]

    operations = [
        migrations.AddField(
            model_name='estoqueitens',
            name='saldo',
            field=models.PositiveIntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
