# Generated by Django 4.0.6 on 2022-09-13 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0004_estoqueitens_saldo'),
    ]

    operations = [
        migrations.AddField(
            model_name='estoqueitens',
            name='obs_estoque',
            field=models.CharField(default='Quem entregou?', max_length=100, verbose_name='Observações'),
        ),
    ]
