# Generated by Django 4.0.6 on 2022-09-13 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0005_estoqueitens_obs_estoque'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estoqueitens',
            name='obs_estoque',
            field=models.CharField(default='------', max_length=100, verbose_name='Observações'),
        ),
    ]
