# Generated by Django 4.0.6 on 2022-09-13 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0007_alter_estoqueitens_obs_estoque'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estoqueitens',
            name='obs_estoque',
            field=models.TextField(blank=True, max_length=150, null=True, verbose_name='Observação'),
        ),
    ]
