# Generated by Django 4.0.6 on 2022-10-16 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0009_estoqueitens_local'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estoqueitens',
            name='local',
        ),
    ]
