# Generated by Django 4.0.6 on 2022-10-20 23:59

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('Cadastro', '0018_alter_produtos_estoque_atl'),
        ('estoque', '0011_estoqueitens_local'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estoqueitens',
            name='local',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estoques', to='Cadastro.local'),
        ),
        migrations.AlterField(
            model_name='estoqueitens',
            name='produto',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='local', chained_model_field='estoque_local', on_delete=django.db.models.deletion.CASCADE, to='Cadastro.produtos'),
        ),
    ]
