# Generated by Django 4.0.6 on 2022-10-27 00:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cadastro', '0021_delete_criarsolicitacao'),
        ('estoque', '0014_remove_estoqueitens_destino_estoque_destino'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estoque',
            name='destino',
        ),
        migrations.AddField(
            model_name='estoque',
            name='est_destino',
            field=models.ForeignKey(blank=True, default=2, on_delete=django.db.models.deletion.CASCADE, related_name='destino_env', to='Cadastro.local'),
        ),
        migrations.AddField(
            model_name='estoqueitens',
            name='destino',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='destino', to='Cadastro.local'),
            preserve_default=False,
        ),
    ]
