# Generated by Django 4.0.6 on 2022-10-27 00:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cadastro', '0021_delete_criarsolicitacao'),
        ('estoque', '0015_remove_estoque_destino_estoque_est_destino_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estoque',
            name='est_destino',
            field=models.ForeignKey(blank=True, default=2, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='destino_env', to='Cadastro.local'),
        ),
    ]
