# Generated by Django 4.0.6 on 2022-10-27 00:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cadastro', '0021_delete_criarsolicitacao'),
        ('estoque', '0016_alter_estoque_est_destino'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estoqueitens',
            name='destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='destino', to='Cadastro.local'),
        ),
    ]
