# Generated by Django 4.0.6 on 2022-10-28 01:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cadastro', '0021_delete_criarsolicitacao'),
        ('estoque', '0018_alter_estoqueitens_destino'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estoqueitens',
            name='destino',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='destino', to='Cadastro.local'),
        ),
    ]
